export ARCH=x86_64
PREFIX=
KERNELDIR=/home/cuju/cuju-kernel/xenial
KERNELSOURCEDIR=
KERNELVERSION=4.4.6+
export CROSS_COMPILE=
export CC=gcc
export LD=ld
export OBJCOPY=objcopy
export AR=ar
KVM_VERSION=kvm-devel
